# Generated by Django 5.1.3 on 2024-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.FileField(default='media/eventDefault.png', upload_to='media/images/'),
        ),
    ]
